version: "3.7"

services:
    api:
        build: ./api
        container_name: api
        image: api
        restart: always
        network_mode: bridge
        expose:
            - 8080

    nginx:
        build: ./nginx
        image: nginx
        container_name: nginx
        network_mode: bridge
        restart: always
        links:
            - "api:api"
        ports:
            - "80:80"
        depends_on:
            - api
